# Generated by Django 6.0.7 on 2026-10-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ambulance_type',
            field=models.CharField(default='Normal', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
